import { PERMISSIONS } from './permissions';

export type RoleType = 'admin' | 'entrepreneur' | 'technician' | 'worker';

// Role definitions with their respective permissions
export const ROLE_PERMISSIONS: Record<RoleType, string[]> = {
  admin: [
    PERMISSIONS.SYSTEM.FULL_ACCESS,
    PERMISSIONS.SYSTEM.CONFIG,
    PERMISSIONS.SYSTEM.AUDIT,
    PERMISSIONS.USERS.MANAGE,
    PERMISSIONS.JOBS.CREATE_ANY,
    PERMISSIONS.JOBS.MANAGE_ANY,
    PERMISSIONS.APPLICATIONS.READ_ANY,
    PERMISSIONS.APPLICATIONS.UPDATE_ANY,
    PERMISSIONS.SELECTION.CONFIGURE,
    PERMISSIONS.PROFILE.READ_ANY,
    PERMISSIONS.PROFILE.UPDATE_ANY,
  ],

  entrepreneur: [
    PERMISSIONS.JOBS.CREATE_ANY,
    PERMISSIONS.JOBS.READ,
    PERMISSIONS.JOBS.UPDATE_OWN,
    PERMISSIONS.JOBS.DELETE_OWN,
    PERMISSIONS.APPLICATIONS.READ_ANY,
    PERMISSIONS.APPLICATIONS.UPDATE_ANY,
    PERMISSIONS.SELECTION.ACCESS,
    PERMISSIONS.SELECTION.VIEW_RESULTS,
    PERMISSIONS.PROFILE.READ_ANY,
    PERMISSIONS.PROFILE.READ_OWN,
    PERMISSIONS.PROFILE.UPDATE_OWN,
  ],

  technician: [
    PERMISSIONS.JOBS.CREATE_WORKER,
    PERMISSIONS.JOBS.READ,
    PERMISSIONS.JOBS.UPDATE_OWN,
    PERMISSIONS.JOBS.DELETE_OWN,
    PERMISSIONS.APPLICATIONS.CREATE,
    PERMISSIONS.APPLICATIONS.READ_ANY,
    PERMISSIONS.APPLICATIONS.UPDATE_ANY,
    PERMISSIONS.APPLICATIONS.READ_OWN,
    PERMISSIONS.SELECTION.ACCESS,
    PERMISSIONS.SELECTION.VIEW_RESULTS,
    PERMISSIONS.PROFILE.READ_OWN,
    PERMISSIONS.PROFILE.UPDATE_OWN,
  ],

  worker: [
    PERMISSIONS.JOBS.CREATE_WORKER,
    PERMISSIONS.JOBS.READ,
    PERMISSIONS.JOBS.UPDATE_OWN,
    PERMISSIONS.JOBS.DELETE_OWN,
    PERMISSIONS.APPLICATIONS.CREATE,
    PERMISSIONS.APPLICATIONS.READ_OWN,
    PERMISSIONS.APPLICATIONS.UPDATE_OWN,
    PERMISSIONS.APPLICATIONS.DELETE_OWN,
    PERMISSIONS.PROFILE.READ_OWN,
    PERMISSIONS.PROFILE.UPDATE_OWN,
  ],
};